
cora:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  dropout: 0.5
  num_epochs: 200
  patience: 30

cora_ml:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 128
  dropout: 0.5
  num_epochs: 200
  patience: 30

citeseer:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 32
  dropout: 0.5
  num_epochs: 200
  patience: 30

polblogs:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  dropout: 0.5
  num_epochs: 200
  patience: 30


pubmed:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  dropout: 0.5
  num_epochs: 200
  patience: 30
