cora:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 64
  num_head: 4
  negative_slope: 0.2
  dropout: 0.6
  num_epochs: 1000
  patience: 100

cora_ml:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 128
  num_head: 4
  negative_slope: 0.2
  dropout: 0.6
  num_epochs: 1000
  patience: 100

citeseer:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  num_head: 4
  negative_slope: 0.2
  dropout: 0.6
  num_epochs: 1000
  patience: 100

polblogs:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  num_head: 4
  negative_slope: 0.2
  dropout: 0.6
  num_epochs: 1000
  patience: 100


pubmed:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 128
  num_head: 8
  negative_slope: 0.1
  dropout: 0.6
  num_epochs: 1000
  patience: 100
