
cora:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  dropout: 0.5
  num_epochs: 300
  patience: 30
  k: 80
  use_dense: False

cora_ml:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 64
  dropout: 0.5
  num_epochs: 300
  patience: 30
  k: 80
  use_dense: False

citeseer:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 32
  dropout: 0.5
  num_epochs: 300
  patience: 30
  k: 50
  use_dense: False

pubmed:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 32
  dropout: 0.5
  num_epochs: 300
  patience: 30
  k: 50
  use_dense: False

