cora:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  dropout: 0.5
  num_epochs: 1000
  patience: 80

cora_ml:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 64
  dropout: 0.7
  num_epochs: 1000
  patience: 80

citeseer:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 32
  dropout: 0.5
  num_epochs: 1000
  patience: 400

polblogs:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  dropout: 0.5
  num_epochs: 1000
  patience: 100


pubmed:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 20
  dropout: 0.5
  num_epochs: 1000
  patience: 100
