cora:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  gamma: 1.0
  beta1: 0.0005
  beta2: 0.0005
  num_hidden: 64
  dropout: 0.6
  num_epochs: 200
  patience: 30


cora_ml:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  gamma: 1.0
  beta1: 0.0005
  beta2: 0.0005
  num_hidden: 128
  dropout: 0.6
  num_epochs: 200
  patience: 30


citeseer:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  gamma: 1.0
  beta1: 0.0005
  beta2: 0.0005
  num_hidden: 128
  dropout: 0.3
  num_epochs: 1000
  patience: 200

polblogs:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  gamma: 1.0
  beta1: 0.0005
  beta2: 0.0005
  num_hidden: 64
  dropout: 0.5
  num_epochs: 200
  patience: 30


pubmed:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  gamma: 1.0
  beta1: 0.0005
  beta2: 0.0005
  num_hidden: 128
  dropout: 0.5
  num_epochs: 200
  patience: 30