
cora:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  dropout: 0.5
  num_epochs: 3000
  patience: 300
  gamma: 0.1
  lambda_: 5
  bias_init: 0

cora_ml:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 128
  dropout: 0.5
  num_epochs: 200
  patience: 30
  gamma: 0.1
  lambda_: 5
  bias_init: 0

citeseer:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 32
  dropout: 0.5
  num_epochs: 200
  patience: 30
  gamma: 0.1
  lambda_: 5
  bias_init: 0

pubmed:
  seed: 15
  learning_rate: 0.01
  weight_decay: 0.0005
  num_layers: 2
  num_hidden: 16
  dropout: 0.5
  num_epochs: 200
  patience: 30
  gamma: 0.1
  lambda_: 5
  bias_init: 0
